
num is 0
[2016年 09月 29日 星期四 17:19:40 CST] dealerclient.py  has closed, startup again!
('192.168.31.247',) (9986,)
error: uncaptured python exception, closing channel <__main__.DealerClient 192.168.31.247:9986 at 0x76341698> (<class 'socket.error'>:[Errno 111] Connection refused [/usr/lib/python2.7/asyncore.py|read|83] [/usr/lib/python2.7/asyncore.py|handle_read_event|446] [/usr/lib/python2.7/asyncore.py|handle_connect_event|454])
close
num is 0
[2016年 09月 29日 星期四 17:19:45 CST] dealerclient.py  has closed, startup again!
('192.168.31.247',) (9986,)
error: uncaptured python exception, closing channel <__main__.DealerClient 192.168.31.247:9986 at 0x76311698> (<class 'socket.error'>:[Errno 111] Connection refused [/usr/lib/python2.7/asyncore.py|read|83] [/usr/lib/python2.7/asyncore.py|handle_read_event|446] [/usr/lib/python2.7/asyncore.py|handle_connect_event|454])
close
num is 0
[2016年 09月 29日 星期四 17:19:50 CST] dealerclient.py  has closed, startup again!
('192.168.31.247',) (9986,)
error: uncaptured python exception, closing channel <__main__.DealerClient 192.168.31.247:9986 at 0x76351698> (<class 'socket.error'>:[Errno 111] Connection refused [/usr/lib/python2.7/asyncore.py|read|83] [/usr/lib/python2.7/asyncore.py|handle_read_event|446] [/usr/lib/python2.7/asyncore.py|handle_connect_event|454])
close
num is 0
[2016年 09月 29日 星期四 17:19:55 CST] dealerclient.py  has closed, startup again!
('192.168.31.247',) (9986,)
error: uncaptured python exception, closing channel <__main__.DealerClient 192.168.31.247:9986 at 0x762c7698> (<class 'socket.error'>:[Errno 111] Connection refused [/usr/lib/python2.7/asyncore.py|read|83] [/usr/lib/python2.7/asyncore.py|handle_read_event|446] [/usr/lib/python2.7/asyncore.py|handle_connect_event|454])
close
num is 0
[2016年 09月 29日 星期四 17:20:00 CST] dealerclient.py  has closed, startup again!
('192.168.31.247',) (9986,)
error: uncaptured python exception, closing channel <__main__.DealerClient 192.168.31.247:9986 at 0x76328698> (<class 'socket.error'>:[Errno 111] Connection refused [/usr/lib/python2.7/asyncore.py|read|83] [/usr/lib/python2.7/asyncore.py|handle_read_event|446] [/usr/lib/python2.7/asyncore.py|handle_connect_event|454])
close
num is 0
[2016年 09月 29日 星期四 17:20:05 CST] dealerclient.py  has closed, startup again!
num is 1
num is 1
num is 1
1403 will killed!
('192.168.31.247',) (9986,)
connect
2003 ('hello',)
handle write 17
2001 (1,)
login success
2010 (1,)
kill state = 0
close
